-- =============================================================================
-- BASELINE — APPLICATION AUTHORIZATION CORE (reviewed reference)
-- =============================================================================
-- Source: captured READ-ONLY from production `avmgtsonawtzebvazgcr` on 2026-07-12
--         via pg_get_functiondef / pg_policies / pg_get_viewdef (AUDIT_REPORTS/16).
-- Scope:  the zero-migration-coverage `app.*` authorization core + compat contract
--         (drift families D1/D2/D10 in AUDIT_REPORTS/18). This is the security-
--         critical part production builds out-of-band with no reproducible migration.
--
-- Status: REVIEWED REFERENCE — this file documents the exact production shape so it
--         can be reviewed in diff and so the forward migrations build on a known base.
--         The AUTHORITATIVE, complete, replay-ready baseline (all schemas, every
--         column/constraint/index of all 64 tables) must be generated by the operator
--         with `supabase db dump` (see supabase/baseline/GENERATE_BASELINE.md) — that
--         command needs a production DB connection string, which this agent must not
--         handle. Hand-transcribing 64 tables would be error-prone; db dump is exact.
--
-- Fresh-environment only. NEVER apply to the existing production database.
-- =============================================================================

-- ── enum ─────────────────────────────────────────────────────────────────────
-- app.app_role — single-role model (production; NOT the E1 multi-role user_roles table)
-- create type app.app_role as enum ('admin','lawyer','client','auditor');  -- confirm ordinals from db dump

-- ── authorization helper functions (EXACT production bodies) ──────────────────
-- These are the SECURITY DEFINER helpers the compat-view and case RLS policies
-- depend on. Non-recursive by design (contrast the archived E1 recursion window).

CREATE OR REPLACE FUNCTION app.get_my_role()
 RETURNS app.app_role
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'app', 'public', 'auth'
AS $function$
  select up.app_role
  from app.user_profiles up
  where up.user_id = auth.uid()
    and up.is_active = true
$function$;

CREATE OR REPLACE FUNCTION app.is_case_lawyer(p_case_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'app', 'public', 'auth'
AS $function$
  select exists (
    select 1 from app.cases c
    where c.case_id = p_case_id and c.lawyer_id = auth.uid()
  )
$function$;

CREATE OR REPLACE FUNCTION app.is_case_member(p_case_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'app', 'public', 'auth'
AS $function$
  select exists (
    select 1 from app.case_members cm
    where cm.case_id = p_case_id and cm.user_id = auth.uid()
  )
$function$;

CREATE OR REPLACE FUNCTION app.can_read_case(p_case_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'app', 'public', 'auth'
AS $function$
  select app.get_my_role() = 'admin'
    or app.is_case_lawyer(p_case_id)
    or app.is_case_member(p_case_id)
    or exists (
      select 1 from app.cases c
      where c.case_id = p_case_id and c.client_id = auth.uid()
    )
$function$;

CREATE OR REPLACE FUNCTION app.can_manage_case(p_case_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'app', 'public', 'auth'
AS $function$
  select app.get_my_role() = 'admin'
    or app.is_case_lawyer(p_case_id)
$function$;

CREATE OR REPLACE FUNCTION app.check_case_upload_access(_case_id uuid)
 RETURNS boolean
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM app.cases c WHERE c.case_id = _case_id
    AND (
      c.client_id = auth.uid() OR
      c.lawyer_id = auth.uid() OR
      EXISTS (SELECT 1 FROM app.user_profiles WHERE user_id = auth.uid() AND app_role::text = 'admin')
    )
  )
  OR EXISTS (
    SELECT 1 FROM app.case_members cm WHERE cm.case_id = _case_id AND cm.user_id = auth.uid()
  );
$function$;

-- ── auth bootstrap (EXACT production body) ────────────────────────────────────
-- Writes app.user_profiles with a fixed 'client' role, idempotent. This is the
-- production body — it differs entirely from every archived E1 handle_new_user.
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO app.user_profiles (user_id, full_name, email, app_role, is_active)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'User'),
    NEW.email,
    'client'::app.app_role,
    true
  )
  ON CONFLICT (user_id) DO NOTHING;
  RETURN NEW;
END;
$function$;

-- create trigger on_auth_user_created after insert on auth.users
--   for each row execute function public.handle_new_user();

-- NOTE: table DDL for app.user_profiles / app.cases / app.client_documents /
-- app.case_members / app.case_messages / app.ai_analysis_runs /
-- app.generated_documents / app.multi_agent_analysis_runs, their RLS policies,
-- the 7 public compat views + INSTEAD OF triggers, public.profile_compat_settings,
-- and storage buckets/policies are intentionally NOT hand-transcribed here — they
-- are produced authoritatively by `supabase db dump` (GENERATE_BASELINE.md). Column
-- summaries and policy predicates are documented in AUDIT_REPORTS/16 for review.
