import { chromium } from "@playwright/test";
import { createIdentity, signInAs, deleteUser, createdUsers, cleanupOrphans } from "./harness-lib.mjs";
await cleanupOrphans();
const me = await createIdentity("lawyer", { fullName: "DbgLogin" });
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const reqs = [];
page.on("request", r => { if (/auth|token|supabase/.test(r.url())) reqs.push(r.method()+" "+r.url().slice(0,90)); });
page.on("response", async r => { if (/auth\/v1\/token/.test(r.url())) reqs.push("RESP "+r.status()+" "+r.url().slice(0,80)); });
const toasts = [];
page.on("console", m => { if (/error|toast/i.test(m.type())) toasts.push(m.text().slice(0,150)); });
await page.goto("http://localhost:8080/login", { waitUntil: "domcontentloaded" });
await page.waitForSelector('input[name="email"]', { timeout: 15000 });
await page.fill('input[name="email"]', me.email);
await page.fill('input[name="password"]', me.password);
await page.click('button[type="submit"]');
await page.waitForTimeout(4000);
const url = page.url();
const bodyText = await page.evaluate(()=> document.body.innerText.slice(0,400));
await page.screenshot({ path: "e2e_final_audit/screenshots/dbg_login2.png" });
console.log("email:", me.email);
console.log("final url:", url);
console.log("bodyText:", bodyText.replace(/\s+/g," ").slice(0,300));
console.log("auth reqs:", JSON.stringify(reqs));
console.log("toasts/console:", JSON.stringify(toasts.slice(0,5)));
// verify the same creds work via supabase-js directly (sanity)
const s = await signInAs(me.email, me.password);
console.log("direct signIn ok:", !!s.accessToken, "err:", s.error || null);
await browser.close();
await deleteUser(me.userId);
