import { chromium } from "@playwright/test";
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const errs = [];
page.on("console", m => errs.push(m.type()+": "+m.text().slice(0,200)));
page.on("pageerror", e => errs.push("PAGEERR: "+String(e).slice(0,200)));
page.on("requestfailed", r => errs.push("REQFAIL: "+r.url().slice(0,120)+" "+(r.failure()?.errorText||"")));
await page.goto("http://localhost:8080/login", { waitUntil: "networkidle", timeout: 30000 }).catch(e=>errs.push("GOTO: "+String(e).slice(0,120)));
await page.waitForTimeout(3000);
const url = page.url();
const title = await page.title().catch(()=> "");
const bodyLen = await page.evaluate(()=> document.body.innerText.length).catch(()=>0);
const inputs = await page.evaluate(()=> Array.from(document.querySelectorAll("input")).map(i=>i.name+"|"+i.type)).catch(()=>[]);
const htmlHead = await page.evaluate(()=> document.documentElement.outerHTML.slice(0,500)).catch(()=> "");
await page.screenshot({ path: "e2e_final_audit/screenshots/dbg_login.png" });
console.log("url:", url, "title:", title, "bodyLen:", bodyLen);
console.log("inputs:", JSON.stringify(inputs));
console.log("errs ("+errs.length+"):", errs.slice(0,15).join("\n"));
console.log("htmlHead:", htmlHead.slice(0,300));
await browser.close();
