import { chromium } from "@playwright/test";
import { createIdentity, signInAs, deleteUser, createdUsers, cleanupOrphans } from "./harness-lib.mjs";
import { servicePublic } from "./staging-client.mjs";
import { mkdirSync } from "node:fs";
mkdirSync("e2e_final_audit/screenshots", { recursive: true });
await cleanupOrphans();
const lawyer = await createIdentity("lawyer", { fullName: "Repro Lawyer" });
const admin = await createIdentity("admin", { fullName: "Repro Admin" });
const sl = await signInAs(lawyer.email, lawyer.password);
const sa = await signInAs(admin.email, admin.password);
const ins = await sl.public.from("cases").insert({ title: "Repro Case", status: "open", case_type: "civil" }).select("id").single();
console.log("provisioned; caseId=", ins.data?.id, "caseErr=", ins.error?.message?.slice(0,60));
const browser = await chromium.launch({ headless: true });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
const cerr = []; page.on("console", m => { if (m.type()==="error") cerr.push(m.text().slice(0,160)); }); page.on("pageerror", e => cerr.push("PE:"+String(e).slice(0,160)));
await page.goto("http://localhost:8080/login", { waitUntil: "networkidle", timeout: 30000 }).catch(e=>console.log("goto err",String(e).slice(0,80)));
console.log("after goto url=", page.url());
await page.waitForTimeout(3000);
const inputs = await page.evaluate(()=>Array.from(document.querySelectorAll("input")).map(i=>i.name+":"+i.type)).catch(()=>[]);
const bodyLen = await page.evaluate(()=>document.body.innerText.length).catch(()=>0);
await page.screenshot({ path:"e2e_final_audit/screenshots/repro_login.png" });
console.log("inputs after 3s:", JSON.stringify(inputs), "bodyLen:", bodyLen);
console.log("console errors:", JSON.stringify(cerr.slice(0,8)));
await browser.close();
await servicePublic.from("cases").delete().eq("id", ins.data?.id).catch(()=>{});
for (const u of createdUsers) await deleteUser(u.id);
console.log("done");
